# Parcial Presencial 

Logan Daniel Beltran Ruiz - 1000382874

In [16]:
import pandas as pd
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

df = pd.read_excel('/content/drive/MyDrive/Computacion estadistica/datos_CE_Parcial1000382874.xlsx')
df.head()

   x  y        CBD Accesion
0  1  1  60.739008       A1
1  2  1  61.969501       A1
2  3  1  58.428784       A1
3  4  1  60.026749       A1
4  5  1  61.413996       A1

In [14]:

formula = ols('CBD ~ Accesion', data=df).fit()
anova_lm(formula)

             df        sum_sq      mean_sq           F        PR(>F)
Accesion    3.0  11753.969772  3917.989924  595.899996  2.788673e-70
Residual  116.0    762.689771     6.574912         NaN           NaN

In [ ]:
df['resid'] = formula.resid